import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'TRUE'
import argparse
import sys
from config.experiment_config import get_training_config
from models.training_utils import train_enkf_transformer_with_config, train_eakf_transformer_with_config


def main():
    parser = argparse.ArgumentParser(
        description="Train Transformer model for EnKF or EAKF",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    
    parser.add_argument("--method", type=str, required=True, choices=['enkf', 'eakf'],
                        help="Training method: enkf or eakf")
    parser.add_argument("--tm", type=float, default=5.0, help="Time window length (seconds)")
    parser.add_argument("--n_samples", type=int, default=100, help="Number of training samples")
    parser.add_argument("--epochs", type=int, default=200, help="Number of epochs")
    parser.add_argument("--batch_size", type=int, default=64, help="Batch size")
    parser.add_argument("--seed", type=int, default=30, help="Random seed (training)")
    parser.add_argument("--sig_p", type=float, default=0.02, help="Model error std (training phase)")
    parser.add_argument("--save", type=str, default=None, help="Model save path (.pth), auto-generated by default")
    parser.add_argument("--verbose", action='store_true', help="Show detailed training info")
    
    args = parser.parse_args()
    
    method_name = args.method.upper()
    print("=" * 80)
    print(f"{method_name} Transformer Model Training")
    print("=" * 80)
    print(f"Training parameters:")
    print(f"  Method: {method_name}")
    print(f"  Time window: {args.tm}s")
    print(f"  Sample count: {args.n_samples}")
    print(f"  Epochs: {args.epochs}")
    print(f"  Batch size: {args.batch_size}")
    print(f"  Random seed: {args.seed}")
    print(f"  Model error sig_p: {args.sig_p}")
    
    config = get_training_config(
        tm=args.tm,
        n_samples=args.n_samples,
        epochs=args.epochs,
        batch_size=args.batch_size,
        seed=args.seed,
        N=100,
        sig_p=args.sig_p,
        sig_m=0.10,
        inflation_factor=1.0,
    )
    
    if args.save is None:
        args.save = f"models/transformer_residual_{args.method}_tm{args.tm}_k5_sp{config.sig_p}_seed{args.seed}.pth"
    
    print(f"  Model save path: {args.save}")
    print("=" * 80)
    
    try:
        if args.method == 'enkf':
            model, history = train_enkf_transformer_with_config(config, model_save_path=args.save)
        else:
            model, history = train_eakf_transformer_with_config(config, model_save_path=args.save)
        
        print("\n" + "=" * 80)
        print(f"{method_name} Transformer training completed!")
        print("=" * 80)
        print(f"Model saved to: {args.save}")
        
        if history:
            final_train_loss = history['train_loss'][-1]
            best_val_loss = min(history['val_loss'])
            epochs_trained = len(history['train_loss'])
            
            print(f"Training statistics:")
            print(f"  Epochs trained: {epochs_trained}")
            print(f"  Final training loss: {final_train_loss:.6f}")
            print(f"  Best validation loss: {best_val_loss:.6f}")
        
        print("=" * 80)
        
    except Exception as e:
        print(f"\nTraining failed: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
